#include "hbox.h"
static const hruntime_symbol_t hruntime_hbox_h3rdparty_symbol[]=
{
//h3rdparty/h3rdparty_argtable3_arg_cmd.c
//h3rdparty/h3rdparty_argtable3_arg_date.c
//h3rdparty/h3rdparty_argtable3_arg_dbl.c
//h3rdparty/h3rdparty_argtable3_arg_dstr.c
//h3rdparty/h3rdparty_argtable3_arg_end.c
//h3rdparty/h3rdparty_argtable3_arg_file.c
//h3rdparty/h3rdparty_argtable3_arg_getopt_long.c
//h3rdparty/h3rdparty_argtable3_arg_hashtable.c
//h3rdparty/h3rdparty_argtable3_arg_int.c
//h3rdparty/h3rdparty_argtable3_arg_lit.c
//h3rdparty/h3rdparty_argtable3_arg_rem.c
//h3rdparty/h3rdparty_argtable3_arg_rex.c
//h3rdparty/h3rdparty_argtable3_arg_str.c
//h3rdparty/h3rdparty_argtable3_argtable3.c
//h3rdparty/h3rdparty_argtable3_arg_utils.c
//h3rdparty/h3rdparty_cjson.c
//h3rdparty/h3rdparty_cjson_port.c
//h3rdparty/h3rdparty_cjsonutils.c
//h3rdparty/h3rdparty_common.c
    {hdefaults_str(h3rdparty_init),(uintptr_t)&h3rdparty_init},
//h3rdparty/h3rdparty_freebsd_elf_header.c
//h3rdparty/h3rdparty_freertos_kernel_croutine.c
//h3rdparty/h3rdparty_freertos_kernel_event_groups.c
//h3rdparty/h3rdparty_freertos_kernel_heap.c
//h3rdparty/h3rdparty_freertos_kernel_list.c
//h3rdparty/h3rdparty_freertos_kernel_queue.c
//h3rdparty/h3rdparty_freertos_kernel_stream_buffer.c
//h3rdparty/h3rdparty_freertos_kernel_tasks.c
//h3rdparty/h3rdparty_freertos_kernel_timers.c
//h3rdparty/h3rdparty_libfdt_fdt_addresses.c
//h3rdparty/h3rdparty_libfdt_fdt.c
//h3rdparty/h3rdparty_libfdt_fdt_check.c
//h3rdparty/h3rdparty_libfdt_fdt_empty_tree.c
//h3rdparty/h3rdparty_libfdt_fdt_overlay.c
//h3rdparty/h3rdparty_libfdt_fdt_ro.c
//h3rdparty/h3rdparty_libfdt_fdt_rw.c
//h3rdparty/h3rdparty_libfdt_fdt_strerror.c
//h3rdparty/h3rdparty_libfdt_fdt_sw.c
//h3rdparty/h3rdparty_libfdt_fdt_wip.c
//h3rdparty/h3rdparty_libqrencode_bitstream.c
//h3rdparty/h3rdparty_libqrencode_mask.c
//h3rdparty/h3rdparty_libqrencode_mmask.c
//h3rdparty/h3rdparty_libqrencode_mqrspec.c
//h3rdparty/h3rdparty_libqrencode_qrencode.c
//h3rdparty/h3rdparty_libqrencode_qrinput.c
//h3rdparty/h3rdparty_libqrencode_qrspec.c
//h3rdparty/h3rdparty_libqrencode_rsecc.c
//h3rdparty/h3rdparty_libqrencode_split.c
//h3rdparty/h3rdparty_lz4_lz4.c
//h3rdparty/h3rdparty_lz4_lz4file.c
//h3rdparty/h3rdparty_lz4_lz4frame.c
//h3rdparty/h3rdparty_lz4_lz4hc.c
//h3rdparty/h3rdparty_lz4_xxhash.c
//h3rdparty/h3rdparty_mqtt_packet.c
//h3rdparty/h3rdparty_pb_common.c
    {hdefaults_str(pb_default_field_callback),(uintptr_t)&pb_default_field_callback},
//h3rdparty/h3rdparty_pb_decode.c
    {hdefaults_str(pb_read),(uintptr_t)&pb_read},
    {hdefaults_str(pb_istream_from_buffer),(uintptr_t)&pb_istream_from_buffer},
    {hdefaults_str(pb_decode_varint32),(uintptr_t)&pb_decode_varint32},
    {hdefaults_str(pb_decode_varint),(uintptr_t)&pb_decode_varint},
    {hdefaults_str(pb_decode_tag),(uintptr_t)&pb_decode_tag},
    {hdefaults_str(pb_skip_field),(uintptr_t)&pb_skip_field},
    {hdefaults_str(pb_make_string_substream),(uintptr_t)&pb_make_string_substream},
    {hdefaults_str(pb_close_string_substream),(uintptr_t)&pb_close_string_substream},
    {hdefaults_str(pb_decode_fixed32),(uintptr_t)&pb_decode_fixed32},
    {hdefaults_str(pb_decode_fixed64),(uintptr_t)&pb_decode_fixed64},
    {hdefaults_str(pb_decode_ex),(uintptr_t)&pb_decode_ex},
    {hdefaults_str(pb_decode),(uintptr_t)&pb_decode},
    {hdefaults_str(pb_release),(uintptr_t)&pb_release},
    {hdefaults_str(pb_decode_bool),(uintptr_t)&pb_decode_bool},
    {hdefaults_str(pb_decode_svarint),(uintptr_t)&pb_decode_svarint},
//h3rdparty/h3rdparty_pb_encode.c
    {hdefaults_str(pb_ostream_from_buffer),(uintptr_t)&pb_ostream_from_buffer},
    {hdefaults_str(pb_write),(uintptr_t)&pb_write},
    {hdefaults_str(pb_encode_tag),(uintptr_t)&pb_encode_tag},
    {hdefaults_str(pb_encode_varint),(uintptr_t)&pb_encode_varint},
    {hdefaults_str(pb_encode_tag_for_field),(uintptr_t)&pb_encode_tag_for_field},
    {hdefaults_str(pb_encode),(uintptr_t)&pb_encode},
    {hdefaults_str(pb_encode_ex),(uintptr_t)&pb_encode_ex},
    {hdefaults_str(pb_encode_submessage),(uintptr_t)&pb_encode_submessage},
    {hdefaults_str(pb_get_encoded_size),(uintptr_t)&pb_get_encoded_size},
    {hdefaults_str(pb_encode_svarint),(uintptr_t)&pb_encode_svarint},
    {hdefaults_str(pb_encode_fixed32),(uintptr_t)&pb_encode_fixed32},
    {hdefaults_str(pb_encode_fixed64),(uintptr_t)&pb_encode_fixed64},
    {hdefaults_str(pb_encode_string),(uintptr_t)&pb_encode_string},
//h3rdparty/h3rdparty_printf.c
    {hdefaults_str(hprintf_set_callback),(uintptr_t)&hprintf_set_callback},
    {hdefaults_str(hprintf),(uintptr_t)&hprintf},
    {hdefaults_str(hsprintf),(uintptr_t)&hsprintf},
    {hdefaults_str(hsnprintf),(uintptr_t)&hsnprintf},
    {hdefaults_str(hvprintf),(uintptr_t)&hvprintf},
    {hdefaults_str(hvsnprintf),(uintptr_t)&hvsnprintf},
    {hdefaults_str(hfctprintf),(uintptr_t)&hfctprintf},
    {hdefaults_str(hvfctprintf),(uintptr_t)&hvfctprintf},
//h3rdparty/h3rdparty_softfloat.c
//h3rdparty/h3rdparty_softfp.c
//h3rdparty/h3rdparty_tlsf_tlsf.c
//h3rdparty/h3rdparty_uriparser_UriCommon.c
//h3rdparty/h3rdparty_uriparser_UriCompare.c
//h3rdparty/h3rdparty_uriparser_UriCopy.c
//h3rdparty/h3rdparty_uriparser_UriEscape.c
//h3rdparty/h3rdparty_uriparser_UriFile.c
//h3rdparty/h3rdparty_uriparser_UriIp4Base.c
//h3rdparty/h3rdparty_uriparser_UriIp4.c
//h3rdparty/h3rdparty_uriparser_UriMemory.c
//h3rdparty/h3rdparty_uriparser_UriNormalizeBase.c
//h3rdparty/h3rdparty_uriparser_UriNormalize.c
//h3rdparty/h3rdparty_uriparser_UriParseBase.c
//h3rdparty/h3rdparty_uriparser_UriParse.c
//h3rdparty/h3rdparty_uriparser_UriQuery.c
//h3rdparty/h3rdparty_uriparser_UriRecompose.c
//h3rdparty/h3rdparty_uriparser_UriResolve.c
//h3rdparty/h3rdparty_uriparser_UriSetFragment.c
//h3rdparty/h3rdparty_uriparser_UriSetHostAuto.c
//h3rdparty/h3rdparty_uriparser_UriSetHostCommon.c
//h3rdparty/h3rdparty_uriparser_UriSetHostIp4.c
//h3rdparty/h3rdparty_uriparser_UriSetHostIp6.c
//h3rdparty/h3rdparty_uriparser_UriSetHostIpFuture.c
//h3rdparty/h3rdparty_uriparser_UriSetHostRegName.c
//h3rdparty/h3rdparty_uriparser_UriSetPath.c
//h3rdparty/h3rdparty_uriparser_UriSetPort.c
//h3rdparty/h3rdparty_uriparser_UriSetQuery.c
//h3rdparty/h3rdparty_uriparser_UriSetScheme.c
//h3rdparty/h3rdparty_uriparser_UriSetUserInfo.c
//h3rdparty/h3rdparty_uriparser_UriShorten.c
//h3rdparty/h3rdparty_uriparser_UriVersion.c
//h3rdparty/h3rdparty_zlib_adler32.c
//h3rdparty/h3rdparty_zlib_compress.c
//h3rdparty/h3rdparty_zlib_crc32.c
//h3rdparty/h3rdparty_zlib_deflate.c
//h3rdparty/h3rdparty_zlib_gzclose.c
//h3rdparty/h3rdparty_zlib_gzlib.c
//h3rdparty/h3rdparty_zlib_gzread.c
//h3rdparty/h3rdparty_zlib_gzwrite.c
//h3rdparty/h3rdparty_zlib_infback.c
//h3rdparty/h3rdparty_zlib_inffast.c
//h3rdparty/h3rdparty_zlib_inflate.c
//h3rdparty/h3rdparty_zlib_inftrees.c
//h3rdparty/h3rdparty_zlib_trees.c
//h3rdparty/h3rdparty_zlib_uncompr.c
//h3rdparty/h3rdparty_zlib_zutil.c
};
