#include "hbox.h"
static const hruntime_symbol_t hruntime_hbox_h3rdparty_symbol[]=
{
//h3rdparty/h3rdparty_argtable3_arg_cmd.c
//h3rdparty/h3rdparty_argtable3_arg_date.c
//h3rdparty/h3rdparty_argtable3_arg_dbl.c
//h3rdparty/h3rdparty_argtable3_arg_dstr.c
//h3rdparty/h3rdparty_argtable3_arg_end.c
//h3rdparty/h3rdparty_argtable3_arg_file.c
//h3rdparty/h3rdparty_argtable3_arg_getopt_long.c
//h3rdparty/h3rdparty_argtable3_arg_hashtable.c
//h3rdparty/h3rdparty_argtable3_arg_int.c
//h3rdparty/h3rdparty_argtable3_arg_lit.c
//h3rdparty/h3rdparty_argtable3_arg_rem.c
//h3rdparty/h3rdparty_argtable3_arg_rex.c
//h3rdparty/h3rdparty_argtable3_arg_str.c
//h3rdparty/h3rdparty_argtable3_argtable3.c
//h3rdparty/h3rdparty_argtable3_arg_utils.c
//h3rdparty/h3rdparty_cjson.c
//h3rdparty/h3rdparty_cjson_port.c
    {hdefaults_str(hcjson_version),(uintptr_t)&hcjson_version},
    {hdefaults_str(hcjson_init_hooks),(uintptr_t)&hcjson_init_hooks},
    {hdefaults_str(hcjson_parse),(uintptr_t)&hcjson_parse},
    {hdefaults_str(hcjson_parse_with_length),(uintptr_t)&hcjson_parse_with_length},
    {hdefaults_str(hcjson_parse_with_opts),(uintptr_t)&hcjson_parse_with_opts},
    {hdefaults_str(hcjson_parse_with_length_opts),(uintptr_t)&hcjson_parse_with_length_opts},
    {hdefaults_str(hcjson_print),(uintptr_t)&hcjson_print},
    {hdefaults_str(hcjson_print_unformatted),(uintptr_t)&hcjson_print_unformatted},
    {hdefaults_str(hcjson_print_buffered),(uintptr_t)&hcjson_print_buffered},
    {hdefaults_str(hcjson_print_preallocated),(uintptr_t)&hcjson_print_preallocated},
    {hdefaults_str(hcjson_delete),(uintptr_t)&hcjson_delete},
    {hdefaults_str(hcjson_get_array_size),(uintptr_t)&hcjson_get_array_size},
    {hdefaults_str(hcjson_get_array_item),(uintptr_t)&hcjson_get_array_item},
    {hdefaults_str(hcjson_get_object_item),(uintptr_t)&hcjson_get_object_item},
    {hdefaults_str(hcjson_get_object_item_casesensitive),(uintptr_t)&hcjson_get_object_item_casesensitive},
    {hdefaults_str(hcjson_has_object_item),(uintptr_t)&hcjson_has_object_item},
    {hdefaults_str(hcjson_get_error_ptr),(uintptr_t)&hcjson_get_error_ptr},
    {hdefaults_str(hcjson_get_string_value),(uintptr_t)&hcjson_get_string_value},
    {hdefaults_str(hcjson_get_number_value),(uintptr_t)&hcjson_get_number_value},
    {hdefaults_str(hcjson_is_invalid),(uintptr_t)&hcjson_is_invalid},
    {hdefaults_str(hcjson_is_false),(uintptr_t)&hcjson_is_false},
    {hdefaults_str(hcjson_is_true),(uintptr_t)&hcjson_is_true},
    {hdefaults_str(hcjson_is_bool),(uintptr_t)&hcjson_is_bool},
    {hdefaults_str(hcjson_is_null),(uintptr_t)&hcjson_is_null},
    {hdefaults_str(hcjson_is_number),(uintptr_t)&hcjson_is_number},
    {hdefaults_str(hcjson_is_string),(uintptr_t)&hcjson_is_string},
    {hdefaults_str(hcjson_is_array),(uintptr_t)&hcjson_is_array},
    {hdefaults_str(hcjson_is_object),(uintptr_t)&hcjson_is_object},
    {hdefaults_str(hcjson_is_raw),(uintptr_t)&hcjson_is_raw},
    {hdefaults_str(hcjson_create_null),(uintptr_t)&hcjson_create_null},
    {hdefaults_str(hcjson_create_true),(uintptr_t)&hcjson_create_true},
    {hdefaults_str(hcjson_create_false),(uintptr_t)&hcjson_create_false},
    {hdefaults_str(hcjson_create_bool),(uintptr_t)&hcjson_create_bool},
    {hdefaults_str(hcjson_create_number),(uintptr_t)&hcjson_create_number},
    {hdefaults_str(hcjson_create_string),(uintptr_t)&hcjson_create_string},
    {hdefaults_str(hcjson_create_raw),(uintptr_t)&hcjson_create_raw},
    {hdefaults_str(hcjson_create_array),(uintptr_t)&hcjson_create_array},
    {hdefaults_str(hcjson_create_object),(uintptr_t)&hcjson_create_object},
    {hdefaults_str(hcjson_create_string_reference),(uintptr_t)&hcjson_create_string_reference},
    {hdefaults_str(hcjson_create_object_reference),(uintptr_t)&hcjson_create_object_reference},
    {hdefaults_str(hcjson_create_array_reference),(uintptr_t)&hcjson_create_array_reference},
    {hdefaults_str(hcjson_create_int_array),(uintptr_t)&hcjson_create_int_array},
    {hdefaults_str(hcjson_create_float_array),(uintptr_t)&hcjson_create_float_array},
    {hdefaults_str(hcjson_create_double_array),(uintptr_t)&hcjson_create_double_array},
    {hdefaults_str(hcjson_create_string_array),(uintptr_t)&hcjson_create_string_array},
    {hdefaults_str(hcjson_add_item_to_array),(uintptr_t)&hcjson_add_item_to_array},
    {hdefaults_str(hcjson_add_item_to_object),(uintptr_t)&hcjson_add_item_to_object},
    {hdefaults_str(hcjson_add_item_to_object_CS),(uintptr_t)&hcjson_add_item_to_object_CS},
    {hdefaults_str(hcjson_add_item_reference_to_array),(uintptr_t)&hcjson_add_item_reference_to_array},
    {hdefaults_str(hcjson_add_item_reference_to_object),(uintptr_t)&hcjson_add_item_reference_to_object},
    {hdefaults_str(hcjson_detach_item_via_pointer),(uintptr_t)&hcjson_detach_item_via_pointer},
    {hdefaults_str(hcjson_detach_item_from_array),(uintptr_t)&hcjson_detach_item_from_array},
    {hdefaults_str(hcjson_delete_item_from_array),(uintptr_t)&hcjson_delete_item_from_array},
    {hdefaults_str(hcjson_detach_item_from_object),(uintptr_t)&hcjson_detach_item_from_object},
    {hdefaults_str(hcjson_detach_item_from_object_casesensitive),(uintptr_t)&hcjson_detach_item_from_object_casesensitive},
    {hdefaults_str(hcjson_delete_item_from_object),(uintptr_t)&hcjson_delete_item_from_object},
    {hdefaults_str(hcjson_delete_item_from_object_casesensitive),(uintptr_t)&hcjson_delete_item_from_object_casesensitive},
    {hdefaults_str(hcjson_insert_item_in_array),(uintptr_t)&hcjson_insert_item_in_array},
    {hdefaults_str(hcjson_replace_item_via_pointer),(uintptr_t)&hcjson_replace_item_via_pointer},
    {hdefaults_str(hcjson_replace_item_in_array),(uintptr_t)&hcjson_replace_item_in_array},
    {hdefaults_str(hcjson_replace_item_in_object),(uintptr_t)&hcjson_replace_item_in_object},
    {hdefaults_str(hcjson_replace_item_in_object_casesensitive),(uintptr_t)&hcjson_replace_item_in_object_casesensitive},
    {hdefaults_str(hcjson_duplicate),(uintptr_t)&hcjson_duplicate},
    {hdefaults_str(hcjson_compare),(uintptr_t)&hcjson_compare},
    {hdefaults_str(hcjson_minify),(uintptr_t)&hcjson_minify},
    {hdefaults_str(hcjson_add_null_to_object),(uintptr_t)&hcjson_add_null_to_object},
    {hdefaults_str(hcjson_add_true_to_object),(uintptr_t)&hcjson_add_true_to_object},
    {hdefaults_str(hcjson_add_false_to_object),(uintptr_t)&hcjson_add_false_to_object},
    {hdefaults_str(hcjson_add_bool_to_object),(uintptr_t)&hcjson_add_bool_to_object},
    {hdefaults_str(hcjson_add_number_to_object),(uintptr_t)&hcjson_add_number_to_object},
    {hdefaults_str(hcjson_add_string_to_object),(uintptr_t)&hcjson_add_string_to_object},
    {hdefaults_str(hcjson_add_raw_to_object),(uintptr_t)&hcjson_add_raw_to_object},
    {hdefaults_str(hcjson_add_object_to_object),(uintptr_t)&hcjson_add_object_to_object},
    {hdefaults_str(hcjson_add_array_to_object),(uintptr_t)&hcjson_add_array_to_object},
    {hdefaults_str(hcjson_set_int_value),(uintptr_t)&hcjson_set_int_value},
    {hdefaults_str(hcjson_set_number_helper),(uintptr_t)&hcjson_set_number_helper},
    {hdefaults_str(hcjson_set_number_value),(uintptr_t)&hcjson_set_number_value},
    {hdefaults_str(hcjson_set_bool_value),(uintptr_t)&hcjson_set_bool_value},
    {hdefaults_str(hcjson_set_valuestring),(uintptr_t)&hcjson_set_valuestring},
    {hdefaults_str(hcjson_array_for_each),(uintptr_t)&hcjson_array_for_each},
    {hdefaults_str(hcjson_malloc),(uintptr_t)&hcjson_malloc},
    {hdefaults_str(hcjson_free),(uintptr_t)&hcjson_free},
    {hdefaults_str(hcjson_utils_get_pointer),(uintptr_t)&hcjson_utils_get_pointer},
    {hdefaults_str(hcjson_utils_get_pointer_casesensitive),(uintptr_t)&hcjson_utils_get_pointer_casesensitive},
    {hdefaults_str(hcjson_utils_generate_patches),(uintptr_t)&hcjson_utils_generate_patches},
    {hdefaults_str(hcjson_utils_generate_patches_casesensitive),(uintptr_t)&hcjson_utils_generate_patches_casesensitive},
    {hdefaults_str(hcjson_utils_add_patch_to_array),(uintptr_t)&hcjson_utils_add_patch_to_array},
    {hdefaults_str(hcjson_utils_apply_patches),(uintptr_t)&hcjson_utils_apply_patches},
    {hdefaults_str(hcjson_utils_merge_patch),(uintptr_t)&hcjson_utils_merge_patch},
    {hdefaults_str(hcjson_utils_merge_patch_casesensitive),(uintptr_t)&hcjson_utils_merge_patch_casesensitive},
    {hdefaults_str(hcjson_utils_generate_merge_patch),(uintptr_t)&hcjson_utils_generate_merge_patch},
    {hdefaults_str(hcjson_utils_generate_merge_patch_casesensitive),(uintptr_t)&hcjson_utils_generate_merge_patch_casesensitive},
    {hdefaults_str(hcjson_utils_find_pointer_from_object_to),(uintptr_t)&hcjson_utils_find_pointer_from_object_to},
    {hdefaults_str(hcjson_utils_sort_bject),(uintptr_t)&hcjson_utils_sort_bject},
    {hdefaults_str(hcjson_utils_sort_object_casesensitive),(uintptr_t)&hcjson_utils_sort_object_casesensitive},
//h3rdparty/h3rdparty_cjsonutils.c
//h3rdparty/h3rdparty_common.c
    {hdefaults_str(h3rdparty_init),(uintptr_t)&h3rdparty_init},
//h3rdparty/h3rdparty_freebsd_elf_header.c
//h3rdparty/h3rdparty_freertos_kernel_croutine.c
//h3rdparty/h3rdparty_freertos_kernel_event_groups.c
//h3rdparty/h3rdparty_freertos_kernel_heap.c
//h3rdparty/h3rdparty_freertos_kernel_list.c
//h3rdparty/h3rdparty_freertos_kernel_queue.c
//h3rdparty/h3rdparty_freertos_kernel_stream_buffer.c
//h3rdparty/h3rdparty_freertos_kernel_tasks.c
//h3rdparty/h3rdparty_freertos_kernel_timers.c
//h3rdparty/h3rdparty_libfdt_fdt_addresses.c
//h3rdparty/h3rdparty_libfdt_fdt.c
//h3rdparty/h3rdparty_libfdt_fdt_check.c
//h3rdparty/h3rdparty_libfdt_fdt_empty_tree.c
//h3rdparty/h3rdparty_libfdt_fdt_overlay.c
//h3rdparty/h3rdparty_libfdt_fdt_ro.c
//h3rdparty/h3rdparty_libfdt_fdt_rw.c
//h3rdparty/h3rdparty_libfdt_fdt_strerror.c
//h3rdparty/h3rdparty_libfdt_fdt_sw.c
//h3rdparty/h3rdparty_libfdt_fdt_wip.c
//h3rdparty/h3rdparty_libqrencode_bitstream.c
//h3rdparty/h3rdparty_libqrencode_mask.c
//h3rdparty/h3rdparty_libqrencode_mmask.c
//h3rdparty/h3rdparty_libqrencode_mqrspec.c
//h3rdparty/h3rdparty_libqrencode_qrencode.c
//h3rdparty/h3rdparty_libqrencode_qrinput.c
//h3rdparty/h3rdparty_libqrencode_qrspec.c
//h3rdparty/h3rdparty_libqrencode_rsecc.c
//h3rdparty/h3rdparty_libqrencode_split.c
//h3rdparty/h3rdparty_lz4_lz4.c
//h3rdparty/h3rdparty_lz4_lz4file.c
//h3rdparty/h3rdparty_lz4_lz4frame.c
//h3rdparty/h3rdparty_lz4_lz4hc.c
//h3rdparty/h3rdparty_lz4_xxhash.c
//h3rdparty/h3rdparty_mqtt_packet.c
//h3rdparty/h3rdparty_pb_common.c
//h3rdparty/h3rdparty_pb_decode.c
//h3rdparty/h3rdparty_pb_encode.c
//h3rdparty/h3rdparty_printf.c
    {hdefaults_str(hprintf_set_callback),(uintptr_t)&hprintf_set_callback},
    {hdefaults_str(hprintf),(uintptr_t)&hprintf},
    {hdefaults_str(hsprintf),(uintptr_t)&hsprintf},
    {hdefaults_str(hsnprintf),(uintptr_t)&hsnprintf},
    {hdefaults_str(hvprintf),(uintptr_t)&hvprintf},
    {hdefaults_str(hvsnprintf),(uintptr_t)&hvsnprintf},
    {hdefaults_str(hfctprintf),(uintptr_t)&hfctprintf},
    {hdefaults_str(hvfctprintf),(uintptr_t)&hvfctprintf},
//h3rdparty/h3rdparty_softfloat.c
//h3rdparty/h3rdparty_softfp.c
//h3rdparty/h3rdparty_tlsf_tlsf.c
//h3rdparty/h3rdparty_uriparser_UriCommon.c
//h3rdparty/h3rdparty_uriparser_UriCompare.c
//h3rdparty/h3rdparty_uriparser_UriCopy.c
//h3rdparty/h3rdparty_uriparser_UriEscape.c
//h3rdparty/h3rdparty_uriparser_UriFile.c
//h3rdparty/h3rdparty_uriparser_UriIp4Base.c
//h3rdparty/h3rdparty_uriparser_UriIp4.c
//h3rdparty/h3rdparty_uriparser_UriMemory.c
//h3rdparty/h3rdparty_uriparser_UriNormalizeBase.c
//h3rdparty/h3rdparty_uriparser_UriNormalize.c
//h3rdparty/h3rdparty_uriparser_UriParseBase.c
//h3rdparty/h3rdparty_uriparser_UriParse.c
//h3rdparty/h3rdparty_uriparser_UriQuery.c
//h3rdparty/h3rdparty_uriparser_UriRecompose.c
//h3rdparty/h3rdparty_uriparser_UriResolve.c
//h3rdparty/h3rdparty_uriparser_UriSetFragment.c
//h3rdparty/h3rdparty_uriparser_UriSetHostAuto.c
//h3rdparty/h3rdparty_uriparser_UriSetHostCommon.c
//h3rdparty/h3rdparty_uriparser_UriSetHostIp4.c
//h3rdparty/h3rdparty_uriparser_UriSetHostIp6.c
//h3rdparty/h3rdparty_uriparser_UriSetHostIpFuture.c
//h3rdparty/h3rdparty_uriparser_UriSetHostRegName.c
//h3rdparty/h3rdparty_uriparser_UriSetPath.c
//h3rdparty/h3rdparty_uriparser_UriSetPort.c
//h3rdparty/h3rdparty_uriparser_UriSetQuery.c
//h3rdparty/h3rdparty_uriparser_UriSetScheme.c
//h3rdparty/h3rdparty_uriparser_UriSetUserInfo.c
//h3rdparty/h3rdparty_uriparser_UriShorten.c
//h3rdparty/h3rdparty_uriparser_UriVersion.c
//h3rdparty/h3rdparty_zlib_adler32.c
//h3rdparty/h3rdparty_zlib_compress.c
//h3rdparty/h3rdparty_zlib_crc32.c
//h3rdparty/h3rdparty_zlib_deflate.c
//h3rdparty/h3rdparty_zlib_gzclose.c
//h3rdparty/h3rdparty_zlib_gzlib.c
//h3rdparty/h3rdparty_zlib_gzread.c
//h3rdparty/h3rdparty_zlib_gzwrite.c
//h3rdparty/h3rdparty_zlib_infback.c
//h3rdparty/h3rdparty_zlib_inffast.c
//h3rdparty/h3rdparty_zlib_inflate.c
//h3rdparty/h3rdparty_zlib_inftrees.c
//h3rdparty/h3rdparty_zlib_trees.c
//h3rdparty/h3rdparty_zlib_uncompr.c
//h3rdparty/h3rdparty_zlib_zutil.c
};
