#include "hbox.h"
static const hruntime_symbol_t hruntime_hbox_h3rdparty_symbol[]=
{
///home/hyh/HCppBox/HCppBox/hbox/hruntime/symbol/../../h3rdparty/h3rdparty_cjson.c
    {hdefaults_str(cJSON_GetErrorPtr),(uintptr_t)&cJSON_GetErrorPtr},
    {hdefaults_str(cJSON_GetStringValue),(uintptr_t)&cJSON_GetStringValue},
    {hdefaults_str(cJSON_IsString),(uintptr_t)&cJSON_IsString},
    {hdefaults_str(cJSON_GetNumberValue),(uintptr_t)&cJSON_GetNumberValue},
    {hdefaults_str(cJSON_IsNumber),(uintptr_t)&cJSON_IsNumber},
    {hdefaults_str(cJSON_Version),(uintptr_t)&cJSON_Version},
    {hdefaults_str(cJSON_InitHooks),(uintptr_t)&cJSON_InitHooks},
    {hdefaults_str(cJSON_Delete),(uintptr_t)&cJSON_Delete},
    {hdefaults_str(cJSON_SetNumberHelper),(uintptr_t)&cJSON_SetNumberHelper},
    {hdefaults_str(cJSON_SetValuestring),(uintptr_t)&cJSON_SetValuestring},
    {hdefaults_str(cJSON_free),(uintptr_t)&cJSON_free},
    {hdefaults_str(cJSON_ParseWithOpts),(uintptr_t)&cJSON_ParseWithOpts},
    {hdefaults_str(cJSON_ParseWithLengthOpts),(uintptr_t)&cJSON_ParseWithLengthOpts},
    {hdefaults_str(cJSON_Parse),(uintptr_t)&cJSON_Parse},
    {hdefaults_str(cJSON_ParseWithLength),(uintptr_t)&cJSON_ParseWithLength},
    {hdefaults_str(cJSON_Print),(uintptr_t)&cJSON_Print},
    {hdefaults_str(cJSON_PrintUnformatted),(uintptr_t)&cJSON_PrintUnformatted},
    {hdefaults_str(cJSON_PrintBuffered),(uintptr_t)&cJSON_PrintBuffered},
    {hdefaults_str(cJSON_PrintPreallocated),(uintptr_t)&cJSON_PrintPreallocated},
    {hdefaults_str(cJSON_GetArraySize),(uintptr_t)&cJSON_GetArraySize},
    {hdefaults_str(cJSON_GetArrayItem),(uintptr_t)&cJSON_GetArrayItem},
    {hdefaults_str(cJSON_GetObjectItem),(uintptr_t)&cJSON_GetObjectItem},
    {hdefaults_str(cJSON_GetObjectItemCaseSensitive),(uintptr_t)&cJSON_GetObjectItemCaseSensitive},
    {hdefaults_str(cJSON_HasObjectItem),(uintptr_t)&cJSON_HasObjectItem},
    {hdefaults_str(cJSON_AddItemToArray),(uintptr_t)&cJSON_AddItemToArray},
    {hdefaults_str(cJSON_AddItemToObject),(uintptr_t)&cJSON_AddItemToObject},
    {hdefaults_str(cJSON_AddItemToObjectCS),(uintptr_t)&cJSON_AddItemToObjectCS},
    {hdefaults_str(cJSON_AddItemReferenceToArray),(uintptr_t)&cJSON_AddItemReferenceToArray},
    {hdefaults_str(cJSON_AddItemReferenceToObject),(uintptr_t)&cJSON_AddItemReferenceToObject},
    {hdefaults_str(cJSON_AddNullToObject),(uintptr_t)&cJSON_AddNullToObject},
    {hdefaults_str(cJSON_CreateNull),(uintptr_t)&cJSON_CreateNull},
    {hdefaults_str(cJSON_AddTrueToObject),(uintptr_t)&cJSON_AddTrueToObject},
    {hdefaults_str(cJSON_CreateTrue),(uintptr_t)&cJSON_CreateTrue},
    {hdefaults_str(cJSON_AddFalseToObject),(uintptr_t)&cJSON_AddFalseToObject},
    {hdefaults_str(cJSON_CreateFalse),(uintptr_t)&cJSON_CreateFalse},
    {hdefaults_str(cJSON_AddBoolToObject),(uintptr_t)&cJSON_AddBoolToObject},
    {hdefaults_str(cJSON_CreateBool),(uintptr_t)&cJSON_CreateBool},
    {hdefaults_str(cJSON_AddNumberToObject),(uintptr_t)&cJSON_AddNumberToObject},
    {hdefaults_str(cJSON_CreateNumber),(uintptr_t)&cJSON_CreateNumber},
    {hdefaults_str(cJSON_AddStringToObject),(uintptr_t)&cJSON_AddStringToObject},
    {hdefaults_str(cJSON_CreateString),(uintptr_t)&cJSON_CreateString},
    {hdefaults_str(cJSON_AddRawToObject),(uintptr_t)&cJSON_AddRawToObject},
    {hdefaults_str(cJSON_CreateRaw),(uintptr_t)&cJSON_CreateRaw},
    {hdefaults_str(cJSON_AddObjectToObject),(uintptr_t)&cJSON_AddObjectToObject},
    {hdefaults_str(cJSON_CreateObject),(uintptr_t)&cJSON_CreateObject},
    {hdefaults_str(cJSON_AddArrayToObject),(uintptr_t)&cJSON_AddArrayToObject},
    {hdefaults_str(cJSON_CreateArray),(uintptr_t)&cJSON_CreateArray},
    {hdefaults_str(cJSON_DetachItemViaPointer),(uintptr_t)&cJSON_DetachItemViaPointer},
    {hdefaults_str(cJSON_DetachItemFromArray),(uintptr_t)&cJSON_DetachItemFromArray},
    {hdefaults_str(cJSON_DeleteItemFromArray),(uintptr_t)&cJSON_DeleteItemFromArray},
    {hdefaults_str(cJSON_DetachItemFromObject),(uintptr_t)&cJSON_DetachItemFromObject},
    {hdefaults_str(cJSON_DetachItemFromObjectCaseSensitive),(uintptr_t)&cJSON_DetachItemFromObjectCaseSensitive},
    {hdefaults_str(cJSON_DeleteItemFromObject),(uintptr_t)&cJSON_DeleteItemFromObject},
    {hdefaults_str(cJSON_DeleteItemFromObjectCaseSensitive),(uintptr_t)&cJSON_DeleteItemFromObjectCaseSensitive},
    {hdefaults_str(cJSON_InsertItemInArray),(uintptr_t)&cJSON_InsertItemInArray},
    {hdefaults_str(cJSON_ReplaceItemViaPointer),(uintptr_t)&cJSON_ReplaceItemViaPointer},
    {hdefaults_str(cJSON_ReplaceItemInArray),(uintptr_t)&cJSON_ReplaceItemInArray},
    {hdefaults_str(cJSON_ReplaceItemInObject),(uintptr_t)&cJSON_ReplaceItemInObject},
    {hdefaults_str(cJSON_ReplaceItemInObjectCaseSensitive),(uintptr_t)&cJSON_ReplaceItemInObjectCaseSensitive},
    {hdefaults_str(cJSON_CreateStringReference),(uintptr_t)&cJSON_CreateStringReference},
    {hdefaults_str(cJSON_CreateObjectReference),(uintptr_t)&cJSON_CreateObjectReference},
    {hdefaults_str(cJSON_CreateArrayReference),(uintptr_t)&cJSON_CreateArrayReference},
    {hdefaults_str(cJSON_CreateIntArray),(uintptr_t)&cJSON_CreateIntArray},
    {hdefaults_str(cJSON_CreateFloatArray),(uintptr_t)&cJSON_CreateFloatArray},
    {hdefaults_str(cJSON_CreateDoubleArray),(uintptr_t)&cJSON_CreateDoubleArray},
    {hdefaults_str(cJSON_CreateStringArray),(uintptr_t)&cJSON_CreateStringArray},
    {hdefaults_str(cJSON_Duplicate),(uintptr_t)&cJSON_Duplicate},
//    {hdefaults_str(cJSON_Duplicate_rec),(uintptr_t)&cJSON_Duplicate_rec},
    {hdefaults_str(cJSON_Minify),(uintptr_t)&cJSON_Minify},
    {hdefaults_str(cJSON_IsInvalid),(uintptr_t)&cJSON_IsInvalid},
    {hdefaults_str(cJSON_IsFalse),(uintptr_t)&cJSON_IsFalse},
    {hdefaults_str(cJSON_IsTrue),(uintptr_t)&cJSON_IsTrue},
    {hdefaults_str(cJSON_IsBool),(uintptr_t)&cJSON_IsBool},
    {hdefaults_str(cJSON_IsNull),(uintptr_t)&cJSON_IsNull},
    {hdefaults_str(cJSON_IsArray),(uintptr_t)&cJSON_IsArray},
    {hdefaults_str(cJSON_IsObject),(uintptr_t)&cJSON_IsObject},
    {hdefaults_str(cJSON_IsRaw),(uintptr_t)&cJSON_IsRaw},
    {hdefaults_str(cJSON_Compare),(uintptr_t)&cJSON_Compare},
    {hdefaults_str(cJSON_malloc),(uintptr_t)&cJSON_malloc},
///home/hyh/HCppBox/HCppBox/hbox/hruntime/symbol/../../h3rdparty/h3rdparty_cjsonutils.c
    {hdefaults_str(cJSONUtils_FindPointerFromObjectTo),(uintptr_t)&cJSONUtils_FindPointerFromObjectTo},
    {hdefaults_str(cJSONUtils_GetPointer),(uintptr_t)&cJSONUtils_GetPointer},
    {hdefaults_str(cJSONUtils_GetPointerCaseSensitive),(uintptr_t)&cJSONUtils_GetPointerCaseSensitive},
    {hdefaults_str(cJSONUtils_ApplyPatches),(uintptr_t)&cJSONUtils_ApplyPatches},
    {hdefaults_str(cJSONUtils_ApplyPatchesCaseSensitive),(uintptr_t)&cJSONUtils_ApplyPatchesCaseSensitive},
    {hdefaults_str(cJSONUtils_AddPatchToArray),(uintptr_t)&cJSONUtils_AddPatchToArray},
    {hdefaults_str(cJSONUtils_GeneratePatches),(uintptr_t)&cJSONUtils_GeneratePatches},
    {hdefaults_str(cJSONUtils_GeneratePatchesCaseSensitive),(uintptr_t)&cJSONUtils_GeneratePatchesCaseSensitive},
    {hdefaults_str(cJSONUtils_SortObject),(uintptr_t)&cJSONUtils_SortObject},
    {hdefaults_str(cJSONUtils_SortObjectCaseSensitive),(uintptr_t)&cJSONUtils_SortObjectCaseSensitive},
    {hdefaults_str(cJSONUtils_MergePatch),(uintptr_t)&cJSONUtils_MergePatch},
    {hdefaults_str(cJSONUtils_MergePatchCaseSensitive),(uintptr_t)&cJSONUtils_MergePatchCaseSensitive},
    {hdefaults_str(cJSONUtils_GenerateMergePatch),(uintptr_t)&cJSONUtils_GenerateMergePatch},
    {hdefaults_str(cJSONUtils_GenerateMergePatchCaseSensitive),(uintptr_t)&cJSONUtils_GenerateMergePatchCaseSensitive},
///home/hyh/HCppBox/HCppBox/hbox/hruntime/symbol/../../h3rdparty/h3rdparty_mqtt_packet.c
//    {hdefaults_str(MQTTSerialize_connectLength),(uintptr_t)&MQTTSerialize_connectLength},
//    {hdefaults_str(MQTTstrlen),(uintptr_t)&MQTTstrlen},
//    {hdefaults_str(MQTTSerialize_connect),(uintptr_t)&MQTTSerialize_connect},
//    {hdefaults_str(MQTTPacket_len),(uintptr_t)&MQTTPacket_len},
//    {hdefaults_str(MQTTPacket_writeChar),(uintptr_t)&MQTTPacket_writeChar},
//    {hdefaults_str(MQTTPacket_encode),(uintptr_t)&MQTTPacket_encode},
//    {hdefaults_str(MQTTPacket_writeCString),(uintptr_t)&MQTTPacket_writeCString},
//    {hdefaults_str(MQTTPacket_writeInt),(uintptr_t)&MQTTPacket_writeInt},
//    {hdefaults_str(MQTTPacket_writeMQTTString),(uintptr_t)&MQTTPacket_writeMQTTString},
//    {hdefaults_str(MQTTDeserialize_connack),(uintptr_t)&MQTTDeserialize_connack},
//    {hdefaults_str(MQTTPacket_readChar),(uintptr_t)&MQTTPacket_readChar},
//    {hdefaults_str(MQTTPacket_decodeBuf),(uintptr_t)&MQTTPacket_decodeBuf},
//    {hdefaults_str(MQTTSerialize_zero),(uintptr_t)&MQTTSerialize_zero},
//    {hdefaults_str(MQTTSerialize_disconnect),(uintptr_t)&MQTTSerialize_disconnect},
//    {hdefaults_str(MQTTSerialize_pingreq),(uintptr_t)&MQTTSerialize_pingreq},
//    {hdefaults_str(MQTTPacket_checkVersion),(uintptr_t)&MQTTPacket_checkVersion},
//    {hdefaults_str(MQTTDeserialize_connect),(uintptr_t)&MQTTDeserialize_connect},
//    {hdefaults_str(MQTTPacket_readMQTTLenString),(uintptr_t)&MQTTPacket_readMQTTLenString},
//    {hdefaults_str(MQTTPacket_readInt),(uintptr_t)&MQTTPacket_readInt},
//    {hdefaults_str(MQTTSerialize_connack),(uintptr_t)&MQTTSerialize_connack},
//    {hdefaults_str(MQTTDeserialize_publish),(uintptr_t)&MQTTDeserialize_publish},
//    {hdefaults_str(MQTTDeserialize_ack),(uintptr_t)&MQTTDeserialize_ack},
//    {hdefaults_str(MQTTPacket_getName),(uintptr_t)&MQTTPacket_getName},
//    {hdefaults_str(MQTTStringFormat_connect),(uintptr_t)&MQTTStringFormat_connect},
//    {hdefaults_str(MQTTStringFormat_connack),(uintptr_t)&MQTTStringFormat_connack},
//    {hdefaults_str(MQTTStringFormat_publish),(uintptr_t)&MQTTStringFormat_publish},
//    {hdefaults_str(MQTTStringFormat_ack),(uintptr_t)&MQTTStringFormat_ack},
//    {hdefaults_str(MQTTStringFormat_subscribe),(uintptr_t)&MQTTStringFormat_subscribe},
//    {hdefaults_str(MQTTStringFormat_suback),(uintptr_t)&MQTTStringFormat_suback},
//    {hdefaults_str(MQTTStringFormat_unsubscribe),(uintptr_t)&MQTTStringFormat_unsubscribe},
//    {hdefaults_str(MQTTPacket_decode),(uintptr_t)&MQTTPacket_decode},
//    {hdefaults_str(MQTTPacket_bufchar),(uintptr_t)&MQTTPacket_bufchar},
//    {hdefaults_str(MQTTPacket_getLenStringLen),(uintptr_t)&MQTTPacket_getLenStringLen},
//    {hdefaults_str(MQTTPacket_equals),(uintptr_t)&MQTTPacket_equals},
//    {hdefaults_str(MQTTPacket_read),(uintptr_t)&MQTTPacket_read},
//    {hdefaults_str(MQTTPacket_readnb),(uintptr_t)&MQTTPacket_readnb},
//    {hdefaults_str(MQTTSerialize_publishLength),(uintptr_t)&MQTTSerialize_publishLength},
//    {hdefaults_str(MQTTSerialize_publish),(uintptr_t)&MQTTSerialize_publish},
//    {hdefaults_str(MQTTSerialize_ack),(uintptr_t)&MQTTSerialize_ack},
//    {hdefaults_str(MQTTSerialize_puback),(uintptr_t)&MQTTSerialize_puback},
//    {hdefaults_str(MQTTSerialize_pubrel),(uintptr_t)&MQTTSerialize_pubrel},
//    {hdefaults_str(MQTTSerialize_pubcomp),(uintptr_t)&MQTTSerialize_pubcomp},
//    {hdefaults_str(MQTTSerialize_subscribeLength),(uintptr_t)&MQTTSerialize_subscribeLength},
//    {hdefaults_str(MQTTSerialize_subscribe),(uintptr_t)&MQTTSerialize_subscribe},
//    {hdefaults_str(MQTTDeserialize_suback),(uintptr_t)&MQTTDeserialize_suback},
//    {hdefaults_str(MQTTDeserialize_subscribe),(uintptr_t)&MQTTDeserialize_subscribe},
//    {hdefaults_str(MQTTSerialize_suback),(uintptr_t)&MQTTSerialize_suback},
//    {hdefaults_str(MQTTSerialize_unsubscribeLength),(uintptr_t)&MQTTSerialize_unsubscribeLength},
//    {hdefaults_str(MQTTSerialize_unsubscribe),(uintptr_t)&MQTTSerialize_unsubscribe},
//    {hdefaults_str(MQTTDeserialize_unsuback),(uintptr_t)&MQTTDeserialize_unsuback},
//    {hdefaults_str(MQTTDeserialize_unsubscribe),(uintptr_t)&MQTTDeserialize_unsubscribe},
//    {hdefaults_str(MQTTSerialize_unsuback),(uintptr_t)&MQTTSerialize_unsuback},
///home/hyh/HCppBox/HCppBox/hbox/hruntime/symbol/../../h3rdparty/h3rdparty_pb_common.c
//    {hdefaults_str(pb_field_iter_begin),(uintptr_t)&pb_field_iter_begin},
//    {hdefaults_str(pb_field_iter_begin_extension),(uintptr_t)&pb_field_iter_begin_extension},
//    {hdefaults_str(pb_field_iter_next),(uintptr_t)&pb_field_iter_next},
//    {hdefaults_str(pb_field_iter_find),(uintptr_t)&pb_field_iter_find},
//    {hdefaults_str(pb_field_iter_find_extension),(uintptr_t)&pb_field_iter_find_extension},
//    {hdefaults_str(pb_field_iter_begin_const),(uintptr_t)&pb_field_iter_begin_const},
//    {hdefaults_str(pb_field_iter_begin_extension_const),(uintptr_t)&pb_field_iter_begin_extension_const},
//    {hdefaults_str(pb_default_field_callback),(uintptr_t)&pb_default_field_callback},
///home/hyh/HCppBox/HCppBox/hbox/hruntime/symbol/../../h3rdparty/h3rdparty_pb_decode.c
//    {hdefaults_str(pb_read),(uintptr_t)&pb_read},
//    {hdefaults_str(pb_istream_from_buffer),(uintptr_t)&pb_istream_from_buffer},
//    {hdefaults_str(pb_decode_varint32),(uintptr_t)&pb_decode_varint32},
//    {hdefaults_str(pb_decode_varint),(uintptr_t)&pb_decode_varint},
//    {hdefaults_str(pb_decode_tag),(uintptr_t)&pb_decode_tag},
//    {hdefaults_str(pb_skip_field),(uintptr_t)&pb_skip_field},
//    {hdefaults_str(pb_make_string_substream),(uintptr_t)&pb_make_string_substream},
//    {hdefaults_str(pb_close_string_substream),(uintptr_t)&pb_close_string_substream},
//    {hdefaults_str(pb_decode_fixed32),(uintptr_t)&pb_decode_fixed32},
//    {hdefaults_str(pb_decode_fixed64),(uintptr_t)&pb_decode_fixed64},
//    {hdefaults_str(pb_decode_ex),(uintptr_t)&pb_decode_ex},
//    {hdefaults_str(pb_decode),(uintptr_t)&pb_decode},
//    {hdefaults_str(pb_release),(uintptr_t)&pb_release},
//    {hdefaults_str(pb_decode_bool),(uintptr_t)&pb_decode_bool},
//    {hdefaults_str(pb_decode_svarint),(uintptr_t)&pb_decode_svarint},
///home/hyh/HCppBox/HCppBox/hbox/hruntime/symbol/../../h3rdparty/h3rdparty_pb_encode.c
//    {hdefaults_str(pb_ostream_from_buffer),(uintptr_t)&pb_ostream_from_buffer},
//    {hdefaults_str(pb_write),(uintptr_t)&pb_write},
//    {hdefaults_str(pb_encode_tag),(uintptr_t)&pb_encode_tag},
//    {hdefaults_str(pb_encode_varint),(uintptr_t)&pb_encode_varint},
//    {hdefaults_str(pb_encode_tag_for_field),(uintptr_t)&pb_encode_tag_for_field},
//    {hdefaults_str(pb_encode),(uintptr_t)&pb_encode},
//    {hdefaults_str(pb_encode_ex),(uintptr_t)&pb_encode_ex},
//    {hdefaults_str(pb_encode_submessage),(uintptr_t)&pb_encode_submessage},
//    {hdefaults_str(pb_get_encoded_size),(uintptr_t)&pb_get_encoded_size},
//    {hdefaults_str(pb_encode_svarint),(uintptr_t)&pb_encode_svarint},
//    {hdefaults_str(pb_encode_fixed32),(uintptr_t)&pb_encode_fixed32},
//    {hdefaults_str(pb_encode_fixed64),(uintptr_t)&pb_encode_fixed64},
//    {hdefaults_str(pb_encode_string),(uintptr_t)&pb_encode_string},
///home/hyh/HCppBox/HCppBox/hbox/hruntime/symbol/../../h3rdparty/h3rdparty_printf.c
    {hdefaults_str(hprintf_set_callback),(uintptr_t)&hprintf_set_callback},
//    {hdefaults_str(h3rdparty_printf_putchar),(uintptr_t)&h3rdparty_printf_putchar},
    {hdefaults_str(hprintf),(uintptr_t)&hprintf},
    {hdefaults_str(hsprintf),(uintptr_t)&hsprintf},
    {hdefaults_str(hsnprintf),(uintptr_t)&hsnprintf},
    {hdefaults_str(hvprintf),(uintptr_t)&hvprintf},
    {hdefaults_str(hvsnprintf),(uintptr_t)&hvsnprintf},
    {hdefaults_str(hfctprintf),(uintptr_t)&hfctprintf},
    {hdefaults_str(hvfctprintf),(uintptr_t)&hvfctprintf},
///home/hyh/HCppBox/HCppBox/hbox/hruntime/symbol/../../h3rdparty/h3rdparty_softfloat.c
//    {hdefaults_str(float16_default_nan),(uintptr_t)&float16_default_nan},
//    {hdefaults_str(float32_default_nan),(uintptr_t)&float32_default_nan},
//    {hdefaults_str(float64_default_nan),(uintptr_t)&float64_default_nan},
//    {hdefaults_str(floatx80_default_nan),(uintptr_t)&floatx80_default_nan},
//    {hdefaults_str(float128_default_nan),(uintptr_t)&float128_default_nan},
//    {hdefaults_str(float_raise),(uintptr_t)&float_raise},
//    {hdefaults_str(float16_is_quiet_nan),(uintptr_t)&float16_is_quiet_nan},
//    {hdefaults_str(float16_is_signaling_nan),(uintptr_t)&float16_is_signaling_nan},
//    {hdefaults_str(float16_maybe_silence_nan),(uintptr_t)&float16_maybe_silence_nan},
//    {hdefaults_str(float32_is_quiet_nan),(uintptr_t)&float32_is_quiet_nan},
//    {hdefaults_str(float32_is_signaling_nan),(uintptr_t)&float32_is_signaling_nan},
//    {hdefaults_str(float32_maybe_silence_nan),(uintptr_t)&float32_maybe_silence_nan},
//    {hdefaults_str(float64_is_quiet_nan),(uintptr_t)&float64_is_quiet_nan},
//    {hdefaults_str(float64_is_signaling_nan),(uintptr_t)&float64_is_signaling_nan},
//    {hdefaults_str(float64_maybe_silence_nan),(uintptr_t)&float64_maybe_silence_nan},
//    {hdefaults_str(floatx80_is_quiet_nan),(uintptr_t)&floatx80_is_quiet_nan},
//    {hdefaults_str(floatx80_is_signaling_nan),(uintptr_t)&floatx80_is_signaling_nan},
//    {hdefaults_str(floatx80_maybe_silence_nan),(uintptr_t)&floatx80_maybe_silence_nan},
//    {hdefaults_str(float128_is_quiet_nan),(uintptr_t)&float128_is_quiet_nan},
//    {hdefaults_str(float128_is_signaling_nan),(uintptr_t)&float128_is_signaling_nan},
//    {hdefaults_str(float128_maybe_silence_nan),(uintptr_t)&float128_maybe_silence_nan},
//    {hdefaults_str(float32_squash_input_denormal),(uintptr_t)&float32_squash_input_denormal},
//    {hdefaults_str(float64_squash_input_denormal),(uintptr_t)&float64_squash_input_denormal},
//    {hdefaults_str(int32_to_float32),(uintptr_t)&int32_to_float32},
//    {hdefaults_str(int32_to_float64),(uintptr_t)&int32_to_float64},
//    {hdefaults_str(int32_to_floatx80),(uintptr_t)&int32_to_floatx80},
//    {hdefaults_str(int32_to_float128),(uintptr_t)&int32_to_float128},
//    {hdefaults_str(int64_to_float32),(uintptr_t)&int64_to_float32},
//    {hdefaults_str(int64_to_float64),(uintptr_t)&int64_to_float64},
//    {hdefaults_str(int64_to_floatx80),(uintptr_t)&int64_to_floatx80},
//    {hdefaults_str(int64_to_float128),(uintptr_t)&int64_to_float128},
//    {hdefaults_str(uint64_to_float32),(uintptr_t)&uint64_to_float32},
//    {hdefaults_str(uint64_to_float64),(uintptr_t)&uint64_to_float64},
//    {hdefaults_str(uint64_to_float128),(uintptr_t)&uint64_to_float128},
//    {hdefaults_str(float32_to_int32),(uintptr_t)&float32_to_int32},
//    {hdefaults_str(float32_to_int32_round_to_zero),(uintptr_t)&float32_to_int32_round_to_zero},
//    {hdefaults_str(float32_to_int16_round_to_zero),(uintptr_t)&float32_to_int16_round_to_zero},
//    {hdefaults_str(float32_to_int64),(uintptr_t)&float32_to_int64},
//    {hdefaults_str(float32_to_uint64),(uintptr_t)&float32_to_uint64},
//    {hdefaults_str(float32_to_uint64_round_to_zero),(uintptr_t)&float32_to_uint64_round_to_zero},
//    {hdefaults_str(float32_to_int64_round_to_zero),(uintptr_t)&float32_to_int64_round_to_zero},
//    {hdefaults_str(float32_to_float64),(uintptr_t)&float32_to_float64},
//    {hdefaults_str(float32_to_floatx80),(uintptr_t)&float32_to_floatx80},
//    {hdefaults_str(float32_to_float128),(uintptr_t)&float32_to_float128},
//    {hdefaults_str(float32_round_to_int),(uintptr_t)&float32_round_to_int},
//    {hdefaults_str(float32_add),(uintptr_t)&float32_add},
//    {hdefaults_str(float32_sub),(uintptr_t)&float32_sub},
//    {hdefaults_str(float32_mul),(uintptr_t)&float32_mul},
//    {hdefaults_str(float32_div),(uintptr_t)&float32_div},
//    {hdefaults_str(float32_rem),(uintptr_t)&float32_rem},
//    {hdefaults_str(float32_muladd),(uintptr_t)&float32_muladd},
//    {hdefaults_str(float32_sqrt),(uintptr_t)&float32_sqrt},
//    {hdefaults_str(float32_exp2),(uintptr_t)&float32_exp2},
//    {hdefaults_str(float64_mul),(uintptr_t)&float64_mul},
//    {hdefaults_str(float64_add),(uintptr_t)&float64_add},
//    {hdefaults_str(float64_to_float32),(uintptr_t)&float64_to_float32},
//    {hdefaults_str(float32_log2),(uintptr_t)&float32_log2},
//    {hdefaults_str(float32_eq),(uintptr_t)&float32_eq},
//    {hdefaults_str(float32_le),(uintptr_t)&float32_le},
//    {hdefaults_str(float32_lt),(uintptr_t)&float32_lt},
//    {hdefaults_str(float32_unordered),(uintptr_t)&float32_unordered},
//    {hdefaults_str(float32_eq_quiet),(uintptr_t)&float32_eq_quiet},
//    {hdefaults_str(float32_le_quiet),(uintptr_t)&float32_le_quiet},
//    {hdefaults_str(float32_lt_quiet),(uintptr_t)&float32_lt_quiet},
//    {hdefaults_str(float32_unordered_quiet),(uintptr_t)&float32_unordered_quiet},
//    {hdefaults_str(float64_to_int32),(uintptr_t)&float64_to_int32},
//    {hdefaults_str(float64_to_int32_round_to_zero),(uintptr_t)&float64_to_int32_round_to_zero},
//    {hdefaults_str(float64_to_int16_round_to_zero),(uintptr_t)&float64_to_int16_round_to_zero},
//    {hdefaults_str(float64_to_int64),(uintptr_t)&float64_to_int64},
//    {hdefaults_str(float64_to_int64_round_to_zero),(uintptr_t)&float64_to_int64_round_to_zero},
//    {hdefaults_str(float16_to_float32),(uintptr_t)&float16_to_float32},
//    {hdefaults_str(float32_to_float16),(uintptr_t)&float32_to_float16},
//    {hdefaults_str(float16_to_float64),(uintptr_t)&float16_to_float64},
//    {hdefaults_str(float64_to_float16),(uintptr_t)&float64_to_float16},
//    {hdefaults_str(float64_to_floatx80),(uintptr_t)&float64_to_floatx80},
//    {hdefaults_str(float64_to_float128),(uintptr_t)&float64_to_float128},
//    {hdefaults_str(float64_round_to_int),(uintptr_t)&float64_round_to_int},
//    {hdefaults_str(float64_trunc_to_int),(uintptr_t)&float64_trunc_to_int},
//    {hdefaults_str(float64_sub),(uintptr_t)&float64_sub},
//    {hdefaults_str(float64_div),(uintptr_t)&float64_div},
//    {hdefaults_str(float64_rem),(uintptr_t)&float64_rem},
//    {hdefaults_str(float64_muladd),(uintptr_t)&float64_muladd},
//    {hdefaults_str(float64_sqrt),(uintptr_t)&float64_sqrt},
//    {hdefaults_str(float64_log2),(uintptr_t)&float64_log2},
//    {hdefaults_str(float64_eq),(uintptr_t)&float64_eq},
//    {hdefaults_str(float64_le),(uintptr_t)&float64_le},
//    {hdefaults_str(float64_lt),(uintptr_t)&float64_lt},
//    {hdefaults_str(float64_unordered),(uintptr_t)&float64_unordered},
//    {hdefaults_str(float64_eq_quiet),(uintptr_t)&float64_eq_quiet},
//    {hdefaults_str(float64_le_quiet),(uintptr_t)&float64_le_quiet},
//    {hdefaults_str(float64_lt_quiet),(uintptr_t)&float64_lt_quiet},
//    {hdefaults_str(float64_unordered_quiet),(uintptr_t)&float64_unordered_quiet},
//    {hdefaults_str(floatx80_to_int32),(uintptr_t)&floatx80_to_int32},
//    {hdefaults_str(floatx80_to_int32_round_to_zero),(uintptr_t)&floatx80_to_int32_round_to_zero},
//    {hdefaults_str(floatx80_to_int64),(uintptr_t)&floatx80_to_int64},
//    {hdefaults_str(floatx80_to_int64_round_to_zero),(uintptr_t)&floatx80_to_int64_round_to_zero},
//    {hdefaults_str(floatx80_to_float32),(uintptr_t)&floatx80_to_float32},
//    {hdefaults_str(floatx80_to_float64),(uintptr_t)&floatx80_to_float64},
//    {hdefaults_str(floatx80_to_float128),(uintptr_t)&floatx80_to_float128},
//    {hdefaults_str(floatx80_round_to_int),(uintptr_t)&floatx80_round_to_int},
//    {hdefaults_str(floatx80_add),(uintptr_t)&floatx80_add},
//    {hdefaults_str(floatx80_sub),(uintptr_t)&floatx80_sub},
//    {hdefaults_str(floatx80_mul),(uintptr_t)&floatx80_mul},
//    {hdefaults_str(floatx80_div),(uintptr_t)&floatx80_div},
//    {hdefaults_str(floatx80_rem),(uintptr_t)&floatx80_rem},
//    {hdefaults_str(floatx80_sqrt),(uintptr_t)&floatx80_sqrt},
//    {hdefaults_str(floatx80_eq),(uintptr_t)&floatx80_eq},
//    {hdefaults_str(floatx80_le),(uintptr_t)&floatx80_le},
//    {hdefaults_str(floatx80_lt),(uintptr_t)&floatx80_lt},
//    {hdefaults_str(floatx80_unordered),(uintptr_t)&floatx80_unordered},
//    {hdefaults_str(floatx80_eq_quiet),(uintptr_t)&floatx80_eq_quiet},
//    {hdefaults_str(floatx80_le_quiet),(uintptr_t)&floatx80_le_quiet},
//    {hdefaults_str(floatx80_lt_quiet),(uintptr_t)&floatx80_lt_quiet},
//    {hdefaults_str(floatx80_unordered_quiet),(uintptr_t)&floatx80_unordered_quiet},
//    {hdefaults_str(float128_to_int32),(uintptr_t)&float128_to_int32},
//    {hdefaults_str(float128_to_int32_round_to_zero),(uintptr_t)&float128_to_int32_round_to_zero},
//    {hdefaults_str(float128_to_int64),(uintptr_t)&float128_to_int64},
//    {hdefaults_str(float128_to_int64_round_to_zero),(uintptr_t)&float128_to_int64_round_to_zero},
//    {hdefaults_str(float128_to_float32),(uintptr_t)&float128_to_float32},
//    {hdefaults_str(float128_to_float64),(uintptr_t)&float128_to_float64},
//    {hdefaults_str(float128_to_floatx80),(uintptr_t)&float128_to_floatx80},
//    {hdefaults_str(float128_round_to_int),(uintptr_t)&float128_round_to_int},
//    {hdefaults_str(float128_add),(uintptr_t)&float128_add},
//    {hdefaults_str(float128_sub),(uintptr_t)&float128_sub},
//    {hdefaults_str(float128_mul),(uintptr_t)&float128_mul},
//    {hdefaults_str(float128_div),(uintptr_t)&float128_div},
//    {hdefaults_str(float128_rem),(uintptr_t)&float128_rem},
//    {hdefaults_str(float128_sqrt),(uintptr_t)&float128_sqrt},
//    {hdefaults_str(float128_eq),(uintptr_t)&float128_eq},
//    {hdefaults_str(float128_le),(uintptr_t)&float128_le},
//    {hdefaults_str(float128_lt),(uintptr_t)&float128_lt},
//    {hdefaults_str(float128_unordered),(uintptr_t)&float128_unordered},
//    {hdefaults_str(float128_eq_quiet),(uintptr_t)&float128_eq_quiet},
//    {hdefaults_str(float128_le_quiet),(uintptr_t)&float128_le_quiet},
//    {hdefaults_str(float128_lt_quiet),(uintptr_t)&float128_lt_quiet},
//    {hdefaults_str(float128_unordered_quiet),(uintptr_t)&float128_unordered_quiet},
//    {hdefaults_str(uint32_to_float32),(uintptr_t)&uint32_to_float32},
//    {hdefaults_str(uint32_to_float64),(uintptr_t)&uint32_to_float64},
//    {hdefaults_str(float32_to_uint32),(uintptr_t)&float32_to_uint32},
//    {hdefaults_str(float32_to_uint32_round_to_zero),(uintptr_t)&float32_to_uint32_round_to_zero},
//    {hdefaults_str(float32_to_int16),(uintptr_t)&float32_to_int16},
//    {hdefaults_str(float32_to_uint16),(uintptr_t)&float32_to_uint16},
//    {hdefaults_str(float32_to_uint16_round_to_zero),(uintptr_t)&float32_to_uint16_round_to_zero},
//    {hdefaults_str(float64_to_uint32),(uintptr_t)&float64_to_uint32},
//    {hdefaults_str(float64_to_uint64),(uintptr_t)&float64_to_uint64},
//    {hdefaults_str(float64_to_uint32_round_to_zero),(uintptr_t)&float64_to_uint32_round_to_zero},
//    {hdefaults_str(float64_to_uint64_round_to_zero),(uintptr_t)&float64_to_uint64_round_to_zero},
//    {hdefaults_str(float64_to_int16),(uintptr_t)&float64_to_int16},
//    {hdefaults_str(float64_to_uint16),(uintptr_t)&float64_to_uint16},
//    {hdefaults_str(float64_to_uint16_round_to_zero),(uintptr_t)&float64_to_uint16_round_to_zero},
//    {hdefaults_str(float32_compare),(uintptr_t)&float32_compare},
//    {hdefaults_str(float32_compare_quiet),(uintptr_t)&float32_compare_quiet},
//    {hdefaults_str(float64_compare),(uintptr_t)&float64_compare},
//    {hdefaults_str(float64_compare_quiet),(uintptr_t)&float64_compare_quiet},
//    {hdefaults_str(floatx80_compare),(uintptr_t)&floatx80_compare},
//    {hdefaults_str(floatx80_compare_quiet),(uintptr_t)&floatx80_compare_quiet},
//    {hdefaults_str(float128_compare),(uintptr_t)&float128_compare},
//    {hdefaults_str(float128_compare_quiet),(uintptr_t)&float128_compare_quiet},
//    {hdefaults_str(float32_min),(uintptr_t)&float32_min},
//    {hdefaults_str(float32_max),(uintptr_t)&float32_max},
//    {hdefaults_str(float32_minnum),(uintptr_t)&float32_minnum},
//    {hdefaults_str(float32_maxnum),(uintptr_t)&float32_maxnum},
//    {hdefaults_str(float32_minnummag),(uintptr_t)&float32_minnummag},
//    {hdefaults_str(float32_maxnummag),(uintptr_t)&float32_maxnummag},
//    {hdefaults_str(float64_min),(uintptr_t)&float64_min},
//    {hdefaults_str(float64_max),(uintptr_t)&float64_max},
//    {hdefaults_str(float64_minnum),(uintptr_t)&float64_minnum},
//    {hdefaults_str(float64_maxnum),(uintptr_t)&float64_maxnum},
//    {hdefaults_str(float64_minnummag),(uintptr_t)&float64_minnummag},
//    {hdefaults_str(float64_maxnummag),(uintptr_t)&float64_maxnummag},
//    {hdefaults_str(float32_scalbn),(uintptr_t)&float32_scalbn},
//    {hdefaults_str(float64_scalbn),(uintptr_t)&float64_scalbn},
//    {hdefaults_str(floatx80_scalbn),(uintptr_t)&floatx80_scalbn},
//    {hdefaults_str(float128_scalbn),(uintptr_t)&float128_scalbn},
///home/hyh/HCppBox/HCppBox/hbox/hruntime/symbol/../../h3rdparty/h3rdparty_softfp.c
//    {hdefaults_str(issignan_sf32),(uintptr_t)&issignan_sf32},
//    {hdefaults_str(isnan_sf32),(uintptr_t)&isnan_sf32},
//    {hdefaults_str(add_sf32),(uintptr_t)&add_sf32},
//    {hdefaults_str(sub_sf32),(uintptr_t)&sub_sf32},
//    {hdefaults_str(mul_sf32),(uintptr_t)&mul_sf32},
//    {hdefaults_str(fma_sf32),(uintptr_t)&fma_sf32},
//    {hdefaults_str(div_sf32),(uintptr_t)&div_sf32},
//    {hdefaults_str(sqrt_sf32),(uintptr_t)&sqrt_sf32},
//    {hdefaults_str(min_sf32),(uintptr_t)&min_sf32},
//    {hdefaults_str(max_sf32),(uintptr_t)&max_sf32},
//    {hdefaults_str(eq_quiet_sf32),(uintptr_t)&eq_quiet_sf32},
//    {hdefaults_str(le_sf32),(uintptr_t)&le_sf32},
//    {hdefaults_str(lt_sf32),(uintptr_t)&lt_sf32},
//    {hdefaults_str(fclass_sf32),(uintptr_t)&fclass_sf32},
//    {hdefaults_str(cvt_sf32_i32),(uintptr_t)&cvt_sf32_i32},
//    {hdefaults_str(cvt_sf32_u32),(uintptr_t)&cvt_sf32_u32},
//    {hdefaults_str(cvt_i32_sf32),(uintptr_t)&cvt_i32_sf32},
//    {hdefaults_str(cvt_u32_sf32),(uintptr_t)&cvt_u32_sf32},
//    {hdefaults_str(cvt_sf32_i64),(uintptr_t)&cvt_sf32_i64},
//    {hdefaults_str(cvt_sf32_u64),(uintptr_t)&cvt_sf32_u64},
//    {hdefaults_str(cvt_i64_sf32),(uintptr_t)&cvt_i64_sf32},
//    {hdefaults_str(cvt_u64_sf32),(uintptr_t)&cvt_u64_sf32},
//    {hdefaults_str(cvt_sf32_i128),(uintptr_t)&cvt_sf32_i128},
//    {hdefaults_str(cvt_sf32_u128),(uintptr_t)&cvt_sf32_u128},
//    {hdefaults_str(cvt_i128_sf32),(uintptr_t)&cvt_i128_sf32},
//    {hdefaults_str(cvt_u128_sf32),(uintptr_t)&cvt_u128_sf32},
//    {hdefaults_str(issignan_sf64),(uintptr_t)&issignan_sf64},
//    {hdefaults_str(isnan_sf64),(uintptr_t)&isnan_sf64},
//    {hdefaults_str(add_sf64),(uintptr_t)&add_sf64},
//    {hdefaults_str(sub_sf64),(uintptr_t)&sub_sf64},
//    {hdefaults_str(mul_sf64),(uintptr_t)&mul_sf64},
//    {hdefaults_str(fma_sf64),(uintptr_t)&fma_sf64},
//    {hdefaults_str(div_sf64),(uintptr_t)&div_sf64},
//    {hdefaults_str(sqrt_sf64),(uintptr_t)&sqrt_sf64},
//    {hdefaults_str(min_sf64),(uintptr_t)&min_sf64},
//    {hdefaults_str(max_sf64),(uintptr_t)&max_sf64},
//    {hdefaults_str(eq_quiet_sf64),(uintptr_t)&eq_quiet_sf64},
//    {hdefaults_str(le_sf64),(uintptr_t)&le_sf64},
//    {hdefaults_str(lt_sf64),(uintptr_t)&lt_sf64},
//    {hdefaults_str(fclass_sf64),(uintptr_t)&fclass_sf64},
//    {hdefaults_str(cvt_sf32_sf64),(uintptr_t)&cvt_sf32_sf64},
//    {hdefaults_str(cvt_sf64_sf32),(uintptr_t)&cvt_sf64_sf32},
//    {hdefaults_str(cvt_sf64_i32),(uintptr_t)&cvt_sf64_i32},
//    {hdefaults_str(cvt_sf64_u32),(uintptr_t)&cvt_sf64_u32},
//    {hdefaults_str(cvt_i32_sf64),(uintptr_t)&cvt_i32_sf64},
//    {hdefaults_str(cvt_u32_sf64),(uintptr_t)&cvt_u32_sf64},
//    {hdefaults_str(cvt_sf64_i64),(uintptr_t)&cvt_sf64_i64},
//    {hdefaults_str(cvt_sf64_u64),(uintptr_t)&cvt_sf64_u64},
//    {hdefaults_str(cvt_i64_sf64),(uintptr_t)&cvt_i64_sf64},
//    {hdefaults_str(cvt_u64_sf64),(uintptr_t)&cvt_u64_sf64},
//    {hdefaults_str(cvt_sf64_i128),(uintptr_t)&cvt_sf64_i128},
//    {hdefaults_str(cvt_sf64_u128),(uintptr_t)&cvt_sf64_u128},
//    {hdefaults_str(cvt_i128_sf64),(uintptr_t)&cvt_i128_sf64},
//    {hdefaults_str(cvt_u128_sf64),(uintptr_t)&cvt_u128_sf64},
//    {hdefaults_str(issignan_sf128),(uintptr_t)&issignan_sf128},
//    {hdefaults_str(isnan_sf128),(uintptr_t)&isnan_sf128},
//    {hdefaults_str(add_sf128),(uintptr_t)&add_sf128},
//    {hdefaults_str(sub_sf128),(uintptr_t)&sub_sf128},
//    {hdefaults_str(mul_sf128),(uintptr_t)&mul_sf128},
//    {hdefaults_str(fma_sf128),(uintptr_t)&fma_sf128},
//    {hdefaults_str(div_sf128),(uintptr_t)&div_sf128},
//    {hdefaults_str(sqrt_sf128),(uintptr_t)&sqrt_sf128},
//    {hdefaults_str(min_sf128),(uintptr_t)&min_sf128},
//    {hdefaults_str(max_sf128),(uintptr_t)&max_sf128},
//    {hdefaults_str(eq_quiet_sf128),(uintptr_t)&eq_quiet_sf128},
//    {hdefaults_str(le_sf128),(uintptr_t)&le_sf128},
//    {hdefaults_str(lt_sf128),(uintptr_t)&lt_sf128},
//    {hdefaults_str(fclass_sf128),(uintptr_t)&fclass_sf128},
//    {hdefaults_str(cvt_sf32_sf128),(uintptr_t)&cvt_sf32_sf128},
//    {hdefaults_str(cvt_sf128_sf32),(uintptr_t)&cvt_sf128_sf32},
//    {hdefaults_str(cvt_sf64_sf128),(uintptr_t)&cvt_sf64_sf128},
//    {hdefaults_str(cvt_sf128_sf64),(uintptr_t)&cvt_sf128_sf64},
//    {hdefaults_str(cvt_sf128_i32),(uintptr_t)&cvt_sf128_i32},
//    {hdefaults_str(cvt_sf128_u32),(uintptr_t)&cvt_sf128_u32},
//    {hdefaults_str(cvt_i32_sf128),(uintptr_t)&cvt_i32_sf128},
//    {hdefaults_str(cvt_u32_sf128),(uintptr_t)&cvt_u32_sf128},
//    {hdefaults_str(cvt_sf128_i64),(uintptr_t)&cvt_sf128_i64},
//    {hdefaults_str(cvt_sf128_u64),(uintptr_t)&cvt_sf128_u64},
//    {hdefaults_str(cvt_i64_sf128),(uintptr_t)&cvt_i64_sf128},
//    {hdefaults_str(cvt_u64_sf128),(uintptr_t)&cvt_u64_sf128},
//    {hdefaults_str(cvt_sf128_i128),(uintptr_t)&cvt_sf128_i128},
//    {hdefaults_str(cvt_sf128_u128),(uintptr_t)&cvt_sf128_u128},
//    {hdefaults_str(cvt_i128_sf128),(uintptr_t)&cvt_i128_sf128},
//    {hdefaults_str(cvt_u128_sf128),(uintptr_t)&cvt_u128_sf128},
};
