import os
import sys
from building import *

# get current directory
cwd = GetCurrentDir()

os.chdir(cwd)

#执行g++
if not sys.platform.startswith("win32") and not sys.platform.startswith("cygwin"):
    Execute("g++ fsgen.cpp -o fsgen")

#生成RC_fs.c
Execute('PATH=.  &&  fsgen fs RC_fs.c')

cflags=''

# The set of source files associated with this SConscript file.
src = Split("""
RC.c
RC_fs.c
""")


path = [cwd, str(Dir('#'))]

group = DefineGroup('HRC', src, depend = [''], CPPPATH = path,CFLAGS=cflags)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
