import os
import sys
from building import *

# get current directory
cwd = GetCurrentDir()

#默认文件路径
if not os.path.isdir(os.getcwd()+"/build/"):
    os.mkdir(os.getcwd()+"/build/")

HRC_RC_FS_PATH=os.getcwd()+"/build/RC_fs.c"

oldcwd=os.getcwd();

#改变目录
os.chdir(cwd)

HRC_FSGEN="fsgen"

#执行g++
if not sys.platform.startswith("win32"):
    Execute("g++ fsgen.cpp -static -static-libgcc  -o fsgen_custom")
    HRC_FSGEN="fsgen_custom"	


#生成RC_fs.c
if 'HRC_FS_ROOT_DIR' in os.environ:
    Execute('PATH=.  &&  '+HRC_FSGEN+' '+os.environ['HRC_FS_ROOT_DIR']+' '+HRC_RC_FS_PATH)
else:
    Execute('PATH=.  &&  '+HRC_FSGEN+' fs '+HRC_RC_FS_PATH)

#恢复目录
os.chdir(oldcwd)

cflags=''

# The set of source files associated with this SConscript file.
src = Glob("RC.c")
src+= Glob(HRC_RC_FS_PATH)

path = [cwd, str(Dir('#'))]

group = DefineGroup('HRC', src, depend = [''], CPPPATH = path,CFLAGS=cflags)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
