from building import *
import os
import sys

#默认不启用此组件
Enable_HBox_CPP=False

if  "Enable_HBox_CPP" in Env:
    Enable_HBox_CPP=True;

if  "Enable_HBox_CPP" in os.environ:
    Enable_HBox_CPP=True;

if not Enable_HBox_CPP:
    group = []
    Return('group')

cwd = GetCurrentDir()
src = Glob('*.c')
src += Glob('*.cpp')
CPPPATH = [
cwd
]

group = DefineGroup('HBox_CPP', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
